use std::path::PathBuf;

use crate::config::{CursorConfig, GtkConfig};
use crate::error::{ThemeError, ThemeResult};
use crate::palette::Palette;

/// Write GTK settings.ini for both GTK3 and GTK4, then signal live reload.
/// Also writes a gtk.css with palette colors so GTK apps can use the theme.
pub fn apply(config: &GtkConfig, cursor: &CursorConfig, palette: &Palette) -> ThemeResult<()> {
    let gtk3_dir = gtk_config_dir("gtk-3.0")?;
    let gtk4_dir = gtk_config_dir("gtk-4.0")?;

    std::fs::create_dir_all(&gtk3_dir)?;
    std::fs::create_dir_all(&gtk4_dir)?;

    // Write settings.ini
    let content = format!(
        r#"[Settings]
gtk-application-prefer-dark-mode={}
gtk-cursor-theme-name={}
gtk-cursor-theme-size={}
gtk-font-name={}
gtk-icon-theme-name={}
"#,
        if config.prefer_dark { "1" } else { "0" },
        cursor.theme,
        cursor.size,
        config.font_name(),
        config.icon_theme(),
    );

    std::fs::write(gtk3_dir.join("settings.ini"), &content)?;
    std::fs::write(gtk4_dir.join("settings.ini"), &content)?;

    // Write gtk.css with palette colors
    write_gtk_css(&gtk3_dir, palette, config.prefer_dark)?;
    write_gtk_css(&gtk4_dir, palette, config.prefer_dark)?;

    signal_gtk_reload()?;

    Ok(())
}

fn write_gtk_css(dir: &PathBuf, palette: &Palette, dark: bool) -> ThemeResult<()> {
    let bg = if dark {
        &palette.base
    } else {
        &palette.surface0
    };
    let fg = if dark { &palette.text } else { &palette.base };
    let selected_bg = &palette.mauve;

    let css = format!(
        r#"/* Generated by Crawl — do not edit manually */
@define-color theme_bg_color {};
@define-color theme_fg_color {};
@define-color theme_selected_bg_color {};
@define-color theme_selected_fg_color {};
@define-color theme_text_color {};
@define-color theme_base_color {};
@define-color theme_unfocused_base_color {};

* {{
    background-color: @theme_bg_color;
    color: @theme_fg_color;
}}

selection {{
    background-color: @theme_selected_bg_color;
    color: @theme_selected_fg_color;
}}

entry, textview {{
    background-color: @theme_base_color;
}}
"#,
        bg.hex_stripped(),
        fg.hex_stripped(),
        selected_bg.hex_stripped(),
        palette.base.hex_stripped(),
        fg.hex_stripped(),
        palette.surface0.hex_stripped(),
        palette.mantle.hex_stripped(),
    );

    std::fs::write(dir.join("gtk.css"), css)?;
    Ok(())
}

fn gtk_config_dir(version: &str) -> ThemeResult<PathBuf> {
    let base = dirs::config_dir()
        .ok_or_else(|| ThemeError::Other("cannot find config directory".into()))?;
    Ok(base.join(version))
}

/// Extended GtkConfig methods.
impl GtkConfig {
    pub fn font_name(&self) -> String {
        self.font_name.clone().unwrap_or_else(|| "Sans 10".into())
    }

    pub fn icon_theme(&self) -> String {
        self.icon_theme
            .clone()
            .unwrap_or_else(|| "Papirus-Dark".into())
    }
}

/// Signal GTK applications of theme change via xsettings D-Bus protocol.
#[cfg(feature = "gtk")]
fn signal_gtk_reload() -> ThemeResult<()> {
    use tracing::warn;

    let rt = tokio::runtime::Builder::new_current_thread()
        .enable_all()
        .build()
        .map_err(|e| ThemeError::Other(format!("tokio runtime: {}", e)))?;

    rt.block_on(async {
        match zbus::Connection::session().await {
            Ok(conn) => {
                let _ = conn
                    .emit_signal(
                        None,
                        "/org/freedesktop/DBus",
                        "org.freedesktop.DBus",
                        "NameOwnerChanged",
                        &(),
                    )
                    .await;
            }
            Err(e) => {
                warn!("Failed to connect to D-Bus session bus: {}", e);
            }
        }
    });

    Ok(())
}

#[cfg(not(feature = "gtk"))]
fn signal_gtk_reload() -> ThemeResult<()> {
    Ok(())
}
