use std::path::PathBuf;

use crate::color::Color;
use crate::error::{ThemeError, ThemeResult};
use crate::palette::Palette;

const NIRI_CONFIG_DIR: &str = ".config/niri";

/// Write niri color config fragment, then signal reload.
///
/// User's `~/.config/niri/config.kdl` should contain:
/// ```kdl
/// include "theme.kdl";
/// ```
pub fn apply(palette: &Palette, accent: &Color) -> ThemeResult<()> {
    let config_dir = niri_config_dir()?;
    let path = config_dir.join("theme.kdl");

    std::fs::create_dir_all(&config_dir)?;

    let content = format!(
        r#"// Auto-generated by Crawl — do not edit directly
// Included from config.kdl:  include "theme.kdl";

preferred-scale-for-cursor {{ cursor-scale 1.0; }}

layout {{
    focus-ring {{ active-color "{accent}"; }}
    border {{ active-color "{accent}"; }}
}}

ui {{
    border {{ active-color "{accent}"; focused-color "{accent}"; }}
    window-marker {{ active-color "{accent}"; }}
}}

background-color {bg}
default-window-background-color {surface}
"#,
        accent = accent.hex(),
        bg = palette.base.hex(),
        surface = palette.surface0.hex(),
    );

    std::fs::write(&path, content)?;

    let _ = std::process::Command::new("niri")
        .args(["msg", "action", "reload-config"])
        .spawn();

    Ok(())
}

fn niri_config_dir() -> ThemeResult<PathBuf> {
    let home =
        dirs::home_dir().ok_or_else(|| ThemeError::Other("cannot find home directory".into()))?;
    Ok(home.join(NIRI_CONFIG_DIR))
}
